### ISSUE TITLE
a friendly note

### ISSUE THREAD

**Issue by hamidb80** [spneshaei/spneshaei#1]
when I saw this sentence `README.md`:
>  I'm currently an undergraduate student in Computer Engineering at Sharif University (the best university in Iran)

this poem came to my mind:
> گيرم پدر تو بود فاضل  **  از فضل پدر تو را چه حاصل؟

Dear mate, the thing that shows your talents or skills is not where you studied or what your skin color is, where you are from, or even who your father is!

**Comment by spneshaei** [comment]
Hi,

Thanks for noting this! Actually, this is in line with what I've seen in many other _about me_ texts belonging to other people, too; many include a reference to their university in their about texts. Also, where one is studying is naturally different to birthplace, skin color, or similar traits, since the latter items are what you don't choose, but on the other hand, people choose their university of studying themselves (or it is indicated by the results of entrance exams, etc.).
Anyways, I'll surely talk with other people and friends who have maintained GitHub repos for a long time, and I will certainly remove this part in case most of them advise me to remove the mention of the university.
Again, thanks for mentioning this to me! It would be great to hear critical comments like this :)

Best,

Parsa

**Comment by hamidb80** [comment]
> many include a reference to their university in their about text

Sure, but I mostly meant the "the best university in Iran" part. 

There's No problem with mentioning the university in my opinion too.
